In [120]:
import numpy as np

# Define constants
ROWS = 4
COLS = 3
GOAL = (0, 2)
RED_STATE = (0, 1)
WALL_STATES = [(2, 1)]
ACTIONS = {"Right":(0, 1), "Down":(1, 0), "Left":(0, -1), "Up":(-1, 0)}  # Right, Down, Left, Up
ACTION_PROBABILITY = 0.7
DISCOUNT_FACTOR = 0.95
STEP_COST = -0.04
EPSILON = 0.0001
PERPENDICULAR_ACTION = {"Right": ("Up", "Down"), "Left": ("Up", "Down"), "Up": ("Left","Right"), "Down": ("Left","Right")}

In [121]:
POLICY = np.array([ 
    ["-", "None ", "None "], 
    ["-", "-", "-"], 
    ["-", "None ", "-"], 
    ["-", "-", "-"] 
])


In [122]:
def is_valid_state(state):
    return state not in WALL_STATES and (0 <= state[0] < ROWS and 0 <= state[1] < COLS)

# Define a function to check if a state is terminal (goal or red state)
def is_terminal_state(state):
    return state == GOAL or state == RED_STATE

# Define a function to get the next state based on action
def get_next_state(state, action):
    next_state = (state[0] + int(action[0]), state[1] + int(action[1]))
    if is_valid_state(next_state):
        return next_state
    else:
        return state

In [123]:
def print_grid(grid, iteration):
    print(f"Iteration {iteration}:")
    print("Utility Values:")
    print(grid)
    print("-------------")
def print_policy(grid, iteration):
    print(f"Iteration {iteration}:")
    print("Policy Grid:")
    print(grid)
    print("-------------")

In [124]:
def value_iteration(output = True, p = ACTION_PROBABILITY):
    converged = False
    iteration = 0
    grid = np.zeros((ROWS, COLS))
    grid[GOAL[0]][GOAL[1]] = 1
    grid[RED_STATE[0]][RED_STATE[1]] = -1
    while not converged:
        new_grid = np.copy(grid)
        max_change = 0
        iteration+=1
        for i in range(ROWS):
            for j in range(COLS):
                state = (i, j)
                if is_terminal_state(state) or not is_valid_state(state):
                    continue
                
                maxUtility = -1000000000000000
                for direction, distance in ACTIONS.items():
                    next_state = get_next_state(state, distance)
                    k =  STEP_COST + DISCOUNT_FACTOR*p*new_grid[next_state[0]][next_state[1]]
                    perpendicular = PERPENDICULAR_ACTION[direction]
                    perpendicular_p = (1 - p)/2
                    for action in perpendicular:
                        
                        next_state = get_next_state(state, ACTIONS[action])
                        k += DISCOUNT_FACTOR*perpendicular_p*new_grid[next_state[0]][next_state[1]]
                    # maxUtility = max(maxUtility, k)
                    if maxUtility < k:
                        POLICY[state[0]][state[1]] = direction
                        maxUtility = k
                    
                # print(maxUtility, state)
                grid[state[0]][state[1]] = maxUtility
                max_change = max(max_change,abs(new_grid[state[0]][state[1]] - grid[state[0]][state[1]]))
        
        # grid[:] = new_grid
        if(output): print_grid(grid, iteration)
        if max_change <= EPSILON:
            converged = True
    print_policy(POLICY, iteration)

                
                

In [125]:
value_iteration()

Iteration 1:
Utility Values:
[[-0.04  -1.     1.   ]
 [-0.04  -0.04   0.625]
 [-0.04   0.    -0.04 ]
 [-0.04  -0.04  -0.04 ]]
-------------
Iteration 2:
Utility Values:
[[-0.078     -1.         1.       ]
 [-0.078      0.227425   0.7083625]
 [-0.078      0.         0.364225 ]
 [-0.078     -0.078     -0.078    ]]
-------------
Iteration 3:
Utility Values:
[[-0.1141     -1.          1.        ]
 [ 0.08900762  0.32096912  0.75834972]
 [-0.1141      0.          0.53486519]
 [-0.1141     -0.1141      0.17997962]]
-------------
Iteration 4:
Utility Values:
[[-0.11945216 -1.          1.        ]
 [ 0.14092597  0.36754066  0.77880294]
 [-0.01332843  0.          0.61673914]
 [-0.148395    0.04716795  0.3250732 ]]
-------------
Iteration 5:
Utility Values:
[[-0.10580616 -1.          1.        ]
 [ 0.18549331  0.3877785   0.78835396]
 [ 0.04991717  0.          0.65367461]
 [-0.0316789   0.18961654  0.42317589]]
-------------
Iteration 6:
Utility Values:
[[-0.07422433 -1.          1.        ]
 [ 0

In [126]:
def policy_iteration():
    for p in range(1, 10):
        print(p/10)
        value_iteration(False, p/10)

                

In [127]:
policy_iteration()

0.1
Iteration 50:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Up' 'Down' 'Right']
 ['Right' 'None ' 'Right']
 ['Up' 'Down' 'Right']]
-------------
0.2
Iteration 52:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Up' 'Down' 'Right']
 ['Right' 'None ' 'Right']
 ['Up' 'Down' 'Right']]
-------------
0.3
Iteration 51:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Down' 'Down' 'Right']
 ['Right' 'None ' 'Up']
 ['Down' 'Right' 'Right']]
-------------
0.4
Iteration 49:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Down' 'Down' 'Right']
 ['Right' 'None ' 'Up']
 ['Down' 'Right' 'Right']]
-------------
0.5
Iteration 50:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Right' 'Down' 'Up']
 ['Down' 'None ' 'Up']
 ['Right' 'Right' 'Up']]
-------------
0.6
Iteration 49:
Policy Grid:
[['Left' 'None ' 'None ']
 ['Right' 'Down' 'Up']
 ['Down' 'None ' 'Up']
 ['Right' 'Right' 'Up']]
-------------
0.7
Iteration 23:
Policy Grid:
[['Down' 'None ' 'None ']
 ['Right' 'Right' 'Up']
 ['Down' 'None ' 'Up']
 ['Right' 'Right' 'Up']]
---